name: Assign PR Creator

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Assign PR Creator
        uses: actions/github-script@v7
        with:
          script: |
            const actor = process.env.GITHUB_ACTOR;
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [actor]
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
